import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import TipList from '../../components/TipList';
import tips from '../../../data/tip';
import { useRouter } from 'next/router';

const TipListCategory: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  if(!id || !Number(id)) {
    return null;
  }

  const categoryId = Number(id)

  const filteredTip = tips.filter((tip) => tip.categoryId === categoryId);

  return (
    <div className={styles.tip}>
      <Head>
        <title>Create Pair Programming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
      </div>

      <main className={styles.tip}>
        <TipList tipList={filteredTip} />
      </main>
      <div>
        <Footer />
      </div>
    </div>
  )
}

export default TipListCategory;