import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import CategoryList from '../components/CategoryList'
import categories from '../../data/categories'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Pair Programming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
      </div>

      <main className={styles.main}>
        <CategoryList categoryList={categories} />
      </main>
      <div>
        <Footer />
      </div>
    </div>
  )
}

export default Home
