import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const WhoAre: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Who we are</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Who we are
        </h1>
        <div className={styles.grid}>
          <p>We are a small company focused on web development.</p>
        </div>
      </main>
      <div>
        <Footer />
      </div>
    </div>
  )
}

export default WhoAre;